print("\t\t\t\t--------------------------------------------------")
print("\t\t\t\t\t\tSTUDENT INFORMATION")
print("\t\t\t\t--------------------------------------------------")
print("\t\t\t\t\t\tNAME\t:\tAKASHRAM")
print("\t\t\t\t\t\tAGE\t:\t17")
print("\t\t\t\t\t\tMOBILE\t:\t7708648772")
print("\t\t\t\t\t\tADDRESS:\taaaaaaaaaaa")
print("\t\t\t\t\t\tEMAIL\t:\tAKASHRAM@GMAIL.COM")
print("\n")
print("\n")
print("\t\t\t\t--------------------------------------------------")
